kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-ultra-custom
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storageaccounttype: UltraSSD_LRS
  kind: Managed
  cachingMode: None
  DiskIOPSReadWrite: "2048"
  DiskMBpsReadWrite: "256"